### ISSUE TITLE
Translation: PL - Polish

### ISSUE THREAD

**Issue by why-are-all-the-usernames-taken-sadface** [ncase/remember#38]
I'm going to try my best to translate this to Polish. Feel free to correct any mistakes you can find!

**Comment by MiloszFilimowski** [comment]
How is it going? Do you need any help?

**Comment by bones384** [comment]
Completely forgot about this account, hah. Thanks for the reminder.
Unfortunately, I lost any progress I had made in an unfortunate accident involving my laptop, and have since forgotten about this project. Seems like I need to re-read the site involved, eh?
Feel free to try it yourself, I apologize for not being able to provide anyything to work off of.

**Comment by MiloszFilimowski** [comment]
I chopped it into smaller pieces and created a fork so it's easier for everyone to contribute. If you ever feel like you could give it a go one more time, here is the new issue: https://github.com/ncase/remember/issues/58
